sudo: false

language: node_js
node_js: node

cache:
  directories:
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - tests/elm-stuff/build-artifacts
    - tests/elm-stuff/packages
    - node_modules

os:
  - linux

install:
  - npm install
  - npm run install
  - cd tests
  - npm install
  - npm run install
  - cd ..

script:
  - npm run ci:test